name = "soccer-app"
main = "src/index.ts"
compatibility_date = "2024-06-01"

[assets]
directory = "./frontend"

[[d1_databases]]
binding = "DB"
database_name = "soccer-db"
database_id = "ea317dac-2cd0-470f-a848-2a8adcae3215"
